### ISSUE TITLE
The principle of gl_PointSize calculation in particle vertex shader?

### ISSUE THREAD

**Issue by CGrapher** [ttnghia/RealTimeFluidRendering#1]
Hi, thanks for your share. When I was studying your code, I was confused at the principle of calculating the size of the sprite（gl_PointSize）in particle.vs.glsl. What principle did you calculate based on? Clould you please recommend some related paper or formula?

`void ComputePointSizeAndPosition(mat4 T)
{
    vec2 xbc;
    vec2 ybc;

    mat4  R = transpose(projectionMatrix * viewMatrix * T);
    float A = dot(R[ 3 ], D * R[ 3 ]);
    float B = -2. * dot(R[ 0 ], D * R[ 3 ]);
    float C = dot(R[ 0 ], D * R[ 0 ]);
    xbc[ 0 ] = (-B - sqrt(B * B - 4. * A * C)) / (2.0 * A);
    xbc[ 1 ] = (-B + sqrt(B * B - 4. * A * C)) / (2.0 * A);
    float sx = abs(xbc[ 0 ] - xbc[ 1 ]) * .5 * u_ScreenWidth;

    A        = dot(R[ 3 ], D * R[ 3 ]);
    B        = -2. * dot(R[ 1 ], D * R[ 3 ]);
    C        = dot(R[ 1 ], D * R[ 1 ]);
    ybc[ 0 ] = (-B - sqrt(B * B - 4. * A * C)) / (2.0 * A);
    ybc[ 1 ] = (-B + sqrt(B * B - 4. * A * C)) / (2.0 * A);
    float sy = abs(ybc[ 0 ] - ybc[ 1 ]) * .5 * u_ScreenHeight;

    float pointSize = ceil(max(sx, sy));
    gl_PointSize = pointSize;
}`

**Comment by ttnghia** [comment]
Hi,

Thanks for reaching out. That shader snippet is for `bounding box computation`. I adapted it from the paper 
> GPU-Based Ray-Casting of Quadratic Surfaces
by Christian Sigg, Tim Weyrich, Mario Botsch, Markus Gross.

Best.
